"use client";

import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useReducer,
  type Dispatch,
  type ReactNode,
} from "react";

import { monthKeyOf, previousMonth, todayIso } from "@/lib/domain/dates";
import { DEFAULT_CURRENCY } from "@/lib/domain/types";
import type {
  CategoryFilterValue,
  Expense,
  ExpenseDraft,
  IsoDate,
  MonthKey,
} from "@/lib/domain/types";
import type { InitialBook } from "@/lib/expenses/initial-book";

export type SheetState =
  | { mode: "closed" }
  | { mode: "create" }
  | { mode: "edit"; expenseId: string };

export type MonthStatus = "loading" | "loaded" | "error";

export interface MonthSlice {
  status: MonthStatus;
  /** Empty while loading or after a failure — never mistaken for "no spending". */
  expenses: Expense[];
}

export interface BookState {
  /**
   * Only months that have been read, or are being read, appear here. A missing
   * month is "not asked for yet", which is a different thing from an empty one:
   * an empty `loaded` month is the empty state (3.5), a missing month is a
   * spinner (4.2).
   */
  months: Record<MonthKey, MonthSlice>;
  viewedMonth: MonthKey;
  filter: CategoryFilterValue;
  sheet: SheetState;
  /** The undo buffer: an expense deleted but still recoverable (6.1, 6.3). */
  pendingDeletion: Expense | null;
  today: IsoDate;
}

export type BookAction =
  | { type: "setMonth"; month: MonthKey }
  | { type: "monthLoading"; months: MonthKey[] }
  | { type: "monthLoaded"; months: MonthKey[]; expenses: Expense[] }
  | { type: "monthFailed"; months: MonthKey[] }
  | { type: "setFilter"; filter: CategoryFilterValue }
  | { type: "openSheet"; sheet: Exclude<SheetState, { mode: "closed" }> }
  | { type: "closeSheet" }
  | { type: "register"; draft: ExpenseDraft; id: string }
  | { type: "adoptExpense"; localId: string; expense: Expense }
  | { type: "dropExpense"; id: string }
  | { type: "edit"; expenseId: string; draft: ExpenseDraft }
  | { type: "replaceExpense"; expense: Expense }
  | { type: "delete"; expenseId: string }
  | { type: "undoDelete" }
  | { type: "finalizeDelete" };

/** How long a deleted expense stays recoverable (6.3). */
export const UNDO_WINDOW_MS = 5000;

/**
 * The id an expense carries while the database has not answered yet.
 *
 * Real ids are UUIDv7 and are generated by Postgres, never here (10.8), so this
 * one is deliberately marked: anything reaching the repository with a `local-`
 * id would be a bug, and it is visible in a test failure rather than silent.
 */
export function newLocalId(): string {
  const random = globalThis.crypto?.randomUUID?.() ?? Math.random().toString(36).slice(2);
  return `local-${random}`;
}

export function isLocalId(id: string): boolean {
  return id.startsWith("local-");
}

/* -------------------------------------------------------------------------- */
/* Selectors                                                                   */
/* -------------------------------------------------------------------------- */

/** The two months one screen needs: the viewed one and the one before it. */
export function windowMonths(month: MonthKey): MonthKey[] {
  return [previousMonth(month), month];
}

/**
 * Everything the header and the list need for `month`, as one flat list.
 *
 * This is what keeps `lib/domain/summary.ts` untouched by any of this: the pure
 * functions still receive a plain array of expenses and never learn that months
 * arrive separately.
 */
export function windowExpenses(state: BookState, month: MonthKey): Expense[] {
  return windowMonths(month).flatMap((key) => state.months[key]?.expenses ?? []);
}

/**
 * The worst status of the window's two months.
 *
 * A month whose "comparativo" has not arrived is not a month whose figures may
 * be presented as final (4.2), so `loading` in either half is `loading` for the
 * screen.
 */
export function windowStatus(state: BookState, month: MonthKey): MonthStatus {
  const statuses = windowMonths(month).map((key) => state.months[key]?.status ?? "loading");
  if (statuses.includes("loading")) return "loading";
  if (statuses.includes("error")) return "error";
  return "loaded";
}

/** True when the window has never been read and there is nothing to show yet. */
export function isWindowLoaded(state: BookState, month: MonthKey): boolean {
  return windowStatus(state, month) === "loaded";
}

/** Every expense the store is holding, across all months. */
export function allExpenses(state: BookState): Expense[] {
  return Object.values(state.months).flatMap((slice) => slice.expenses);
}

export function findExpense(state: BookState, id: string): Expense | null {
  return allExpenses(state).find((e) => e.id === id) ?? null;
}

/* -------------------------------------------------------------------------- */
/* Reducer helpers                                                             */
/* -------------------------------------------------------------------------- */

type Months = Record<MonthKey, MonthSlice>;

function markMonths(months: Months, keys: MonthKey[], status: MonthStatus): Months {
  const next = { ...months };
  for (const key of keys) {
    // A month that already has data keeps it while it reloads: emptying it would
    // flash the book to zero on every refresh (9.5).
    next[key] = { status, expenses: next[key]?.expenses ?? [] };
  }
  return next;
}

function putExpense(months: Months, expense: Expense): Months {
  const key = monthKeyOf(expense.date);
  const slice = months[key];

  return {
    ...months,
    [key]: {
      // A month the user just wrote into but has never read is still unread; the
      // action layer will load it, and the optimistic row survives the merge.
      status: slice?.status ?? "loading",
      expenses: [...(slice?.expenses ?? []), expense],
    },
  };
}

function removeExpense(months: Months, id: string): Months {
  const next: Months = {};
  for (const [key, slice] of Object.entries(months)) {
    next[key] = { ...slice, expenses: slice.expenses.filter((e) => e.id !== id) };
  }
  return next;
}

/** Blank descriptions are stored as absent, never as "" (1.7, 1.8). */
function cleanDescription(value: string | undefined): string | undefined {
  const trimmed = value?.trim();
  return trimmed ? trimmed : undefined;
}

/**
 * Keeps the filter only while the selected category still has something in the
 * viewed month; otherwise falls back to "todas" (7.7).
 */
function stillPresent(
  state: BookState,
  month: MonthKey,
  filter: CategoryFilterValue,
): CategoryFilterValue {
  if (filter === "todas") return "todas";
  const survives = windowExpenses(state, month).some(
    (e) => e.categoryId === filter && monthKeyOf(e.date) === month,
  );
  return survives ? filter : "todas";
}

/* -------------------------------------------------------------------------- */
/* Initial state                                                               */
/* -------------------------------------------------------------------------- */

/**
 * The store starts from what the server already read (3.1): the viewed month and
 * the one before it, both `loaded`, so the book paints complete.
 */
export function createInitialState(initial: InitialBook): BookState {
  const status: MonthStatus = initial.error ? "error" : "loaded";
  const months: Months = {};

  for (const key of windowMonths(initial.month)) {
    months[key] = {
      status,
      expenses: initial.expenses.filter((e) => monthKeyOf(e.date) === key),
    };
  }

  return {
    months,
    viewedMonth: initial.month,
    filter: "todas",
    sheet: { mode: "closed" },
    pendingDeletion: null,
    today: initial.today,
  };
}

/** An `InitialBook` from a bare list of expenses. Used by tests and by T11. */
export function bookFrom(expenses: Expense[], today: IsoDate = todayIso()): InitialBook {
  return { month: monthKeyOf(today), today, expenses, error: false };
}

/* -------------------------------------------------------------------------- */
/* Reducer                                                                     */
/* -------------------------------------------------------------------------- */

export function bookReducer(state: BookState, action: BookAction): BookState {
  switch (action.type) {
    case "setMonth": {
      // The book never moves past the month containing today (4.5).
      if (action.month > monthKeyOf(state.today)) return state;
      if (action.month === state.viewedMonth) return state;
      // Changing month always clears the filter (7.6).
      return { ...state, viewedMonth: action.month, filter: "todas" };
    }

    case "monthLoading":
      return { ...state, months: markMonths(state.months, action.months, "loading") };

    case "monthLoaded": {
      const months = { ...state.months };
      for (const key of action.months) {
        months[key] = {
          status: "loaded",
          expenses: action.expenses.filter((e) => monthKeyOf(e.date) === key),
        };
      }
      return { ...state, months };
    }

    case "monthFailed":
      // The data already held stays put; only the status changes (4.4, 9.5).
      return { ...state, months: markMonths(state.months, action.months, "error") };

    case "setFilter":
      return { ...state, filter: action.filter };

    case "openSheet":
      return { ...state, sheet: action.sheet };

    case "closeSheet":
      return { ...state, sheet: { mode: "closed" } };

    case "register": {
      const description = cleanDescription(action.draft.description);
      const expense: Expense = {
        id: action.id,
        amount: action.draft.amount,
        // The one place an expense is built, and so the one place the currency
        // is decided (10.3).
        currency: DEFAULT_CURRENCY,
        categoryId: action.draft.categoryId,
        ...(description === undefined ? {} : { description }),
        date: action.draft.date,
        createdAt: Date.now(),
      };

      return {
        ...state,
        months: putExpense(state.months, expense),
        sheet: { mode: "closed" },
        // Follow the expense so it is never recorded out of sight (5.6).
        viewedMonth: monthKeyOf(expense.date),
      };
    }

    case "adoptExpense": {
      /*
       * The database answered: the provisional row becomes the stored one.
       *
       * `createdAt` is kept from the optimistic row rather than taken from the
       * response, so adopting an id cannot make the row jump to another position
       * in its day (5.3).
       */
      const local = findExpense(state, action.localId);
      if (!local) return state;

      const adopted: Expense = { ...action.expense, createdAt: local.createdAt };
      return {
        ...state,
        months: putExpense(removeExpense(state.months, action.localId), adopted),
      };
    }

    case "dropExpense":
      // A write that failed: the row leaves the book, which then shows only what
      // is actually stored (5.4).
      return { ...state, months: removeExpense(state.months, action.id) };

    case "edit": {
      const existing = findExpense(state, action.expenseId);
      if (!existing) return state;

      const edited: Expense = {
        ...existing,
        amount: action.draft.amount,
        categoryId: action.draft.categoryId,
        description: cleanDescription(action.draft.description),
        date: action.draft.date,
      };

      return {
        ...state,
        // Removed and re-put: an edit may move the expense to another month.
        months: putExpense(removeExpense(state.months, action.expenseId), edited),
        sheet: { mode: "closed" },
        viewedMonth: monthKeyOf(action.draft.date),
      };
    }

    case "replaceExpense":
      return {
        ...state,
        months: putExpense(removeExpense(state.months, action.expense.id), action.expense),
      };

    case "delete": {
      const expense = findExpense(state, action.expenseId);
      if (!expense) return state;

      const next: BookState = {
        ...state,
        months: removeExpense(state.months, action.expenseId),
        pendingDeletion: expense,
        sheet: { mode: "closed" },
      };

      return { ...next, filter: stillPresent(next, next.viewedMonth, next.filter) };
    }

    case "undoDelete": {
      if (!state.pendingDeletion) return state;
      // Order derives from `date` and `createdAt`, so putting it back restores
      // the expense to exactly where it was (6.5).
      return {
        ...state,
        months: putExpense(state.months, state.pendingDeletion),
        pendingDeletion: null,
      };
    }

    case "finalizeDelete":
      return state.pendingDeletion === null ? state : { ...state, pendingDeletion: null };

    default:
      return state;
  }
}

/* -------------------------------------------------------------------------- */
/* Provider                                                                    */
/* -------------------------------------------------------------------------- */

const BookContext = createContext<{
  state: BookState;
  dispatch: Dispatch<BookAction>;
} | null>(null);

export function BookProvider({
  children,
  initial,
}: {
  children: ReactNode;
  initial: InitialBook;
}) {
  const [state, dispatch] = useReducer(bookReducer, initial, createInitialState);

  /*
   * The undo timer lives here rather than in the reducer: a reducer that
   * schedules timers is no longer pure, and no longer testable as one.
   */
  useEffect(() => {
    if (!state.pendingDeletion) return;
    const timer = setTimeout(() => dispatch({ type: "finalizeDelete" }), UNDO_WINDOW_MS);
    return () => clearTimeout(timer);
  }, [state.pendingDeletion]);

  const value = useMemo(() => ({ state, dispatch }), [state]);

  return <BookContext.Provider value={value}>{children}</BookContext.Provider>;
}

export function useBook() {
  const value = useContext(BookContext);
  if (!value) throw new Error("useBook must be used inside <BookProvider>");
  return value;
}

export type { Expense, ExpenseDraft };
